# Generated by Django 3.2.6 on 2021-08-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20210811_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['id', 'name'], 'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
    ]
